config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # home/about pages

  root 'application#home', as: 'home'
  get '/about', to: 'application#about', as: 'about'

  # years

  get '/years', to: 'years#years', as: 'years'

  get '/1990', to: 'years#y_1990'
  get '/1991', to: 'years#y_1991'
  get '/1992', to: 'years#y_1992'
  get '/1993', to: 'years#y_1993'
  get '/1994', to: 'years#y_1994'
  get '/1995', to: 'years#y_1995'
  get '/1996', to: 'years#y_1996'
  get '/1997', to: 'years#y_1997'
  get '/1998', to: 'years#y_1998'
  get '/1999', to: 'years#y_1999'

  # login stuff

  get '/login', to: 'sessions#login', as: 'login'
  post '/login', to: 'sessions#logging_in', as: 'logging_in'
  delete '/', to: 'sessions#log_out', as: "log_out"

  # users

  resources :users, only: [:create]
  get '/favorites', to: 'users#favorites', as: 'favorites'
  get '/create_account', to: 'users#create_account', as: 'create_account'

  # user favorites

  post '/favorites', to: 'user_favorites#add_to_favorites', as: 'add_to_favorites'
  delete '/user_favorite', to: 'user_favorites#remove_from_favorites', as: 'remove_from_favorites'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :user_favorites
  has_many :users, through: :user_favorites
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :user_favorites
  has_many :users, through: :user_favorites
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :user_favorites
  has_many :users, through: :user_favorites
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_favorites
  has_many :movies, through: :user_favorites
  has_many :games, through: :user_favorites
  has_many :songs, through: :user_favorites

  validates :username, presence: true
  validates :username, uniqueness: true

  def has_any_favorites? 
    if self.user_favorites.empty? == true 
      return false
    else
      return true
    end
  end

end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie, optional: true
  belongs_to :game, optional: true
  belongs_to :song, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def home
  end

  def about
  end

  private

  def current_user
    @logged_in_user = User.find_by(id: session[:user_id]) 
  end 
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login # renders log-in page
  end

  def logging_in # logs user in
    @user = User.find_by(username: params[:session][:username])
    if @user 
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash[:errors] = ["Username doesn't exist, please try again"]
      redirect_to login_path
    end
  end

  def log_out # logs user out
    session[:user_id] = nil
    redirect_to home_path
  end

  private 

end

app/controllers/user_favorites_controller.rb
class UserFavoritesController < ApplicationController

  def add_to_favorites
    check_if_favorite(user_favorite_params)
  end

  def remove_from_favorites
    if params[:user_favorite][:movie_id]
      @favorite = @logged_in_user.user_favorites.find_by(movie_id: params[:user_favorite][:movie_id])
      @favorite.destroy
      redirect_to request.referrer
    elsif params[:user_favorite][:song_id]
      @favorite = @logged_in_user.user_favorites.find_by(song_id: params[:user_favorite][:song_id])
      @favorite.destroy
      redirect_to request.referrer
    elsif params[:user_favorite][:game_id]
      @favorite = @logged_in_user.user_favorites.find_by(game_id: params[:user_favorite][:game_id])
      @favorite.destroy
      redirect_to request.referrer
    end
  end

  private

    def user_favorite_params
      params.require(:user_favorite).permit(:user_id, :movie_id, :song_id, :game_id)
    end

    def check_if_favorite(params)
      if params[:movie_id]
        check_movie(params)
      elsif params[:song_id]
        check_song(params)
      elsif params[:game_id]
        check_game(params)
      end
    end

      def check_movie(params)
        if @logged_in_user.user_favorites.where(movie_id: params[:movie_id]).empty?
          @user_favorite = UserFavorite.create(user_id: session[:user_id])
          @user_favorite.update(user_favorite_params)
          # redirect_to request.referrer
        else
          flash[:errors] = ["This item is already in your favorites"]
          redirect_to request.referrer
        end
      end

      def check_song(params)
        if @logged_in_user.user_favorites.where(song_id: params[:song_id]).empty?
          @user_favorite = UserFavorite.create(user_id: session[:user_id])
          @user_favorite.update(user_favorite_params)
          # redirect_to request.referrer
        else
          flash[:errors] = ["This item is already in your favorites"]
          redirect_to request.referrer
        end
      end

      def check_game(params)
        if @logged_in_user.user_favorites.where(game_id: params[:game_id]).empty?
          @user_favorite = UserFavorite.create(user_id: session[:user_id])
          @user_favorite.update(user_favorite_params)
          # redirect_to request.referrer
        else
          flash[:errors] = ["This item is already in your favorites"]
          redirect_to request.referrer
        end
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def favorites #favorites page
    if @logged_in_user
      @favorite_movies = @logged_in_user.movies 
      @favorite_songs = @logged_in_user.songs 
      @favorite_games = @logged_in_user.games 
    else
      flash[:errors] = ["You must be logged in to view your favorites page. Create an account?"]
      redirect_to create_account_path
    end
  end

  def create_account
    @user = User.new
  end

  def create 
    @user = User.create(user_params)

    if @user.valid?
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to create_account_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:username)
    end

end

app/controllers/years_controller.rb
class YearsController < ApplicationController

  def years
    
  end

  def y_1990
    year_info_find(1990)
  end

  def y_1991
    year_info_find(1991)
  end

  def y_1992
    year_info_find(1992)
  end

  def y_1993
    year_info_find(1993)
  end

  def y_1994
    year_info_find(1994)
  end

  def y_1995
    year_info_find(1995)
  end

  def y_1996
    year_info_find(1996)
  end

  def y_1997
    year_info_find(1997)
  end

  def y_1998
    year_info_find(1998)
  end

  def y_1999
    year_info_find(1999)
  end

  private

    def year_info_find(year)
      @year = year
      @movies = Movie.where(release_year: year)
      @songs = Song.where(release_year: year)
      @games = Game.where(release_year: year)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<% if @logged_in_user %>
  <h1 class="home-page-welcome">Welcome to the 90s, <%= @logged_in_user.username %>!</h1>
<% else %>
  <h1 class="home-page-welcome">Welcome to the 90s!</h1>
<% end %>

<div class="home-page-container">
  <div class="home-page-blurb">
    <p>Do you often find yourself pining away for the "good old days"?</p>
    
    <p>Do you miss the warm, comforting glow of a CRT television screen?</p>
    
    <p>Do you think video games peaked in the 16 and 32-bit eras?</p>
    
    <p>If so, you've come to the right place.</p>

    <p>Click on "Years" on the navigation bar at the top of the page to get started. 🤙</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>90s Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <% greetings = ["Sup", "Hang tight", "Keep it rad", "Booyah", "You da bomb", "WAZZUUUUUUP", "Don't touch that dial", "You've got mail", "It wasn't me", "Totally tubuluar", "Gnarly", "Bodacious", "Keep it real", "Don't have a cow", "Eat my shorts", "No Duh", "Take a chill pill", "Let's bounce", "Oh snap", "Bling bling", "What's the 411", "Talk to the hand", "I'm totally buggin'", "All that and a bag of chips", "Cowabunga", "Radical", "As if", "Let's kick it", "Who's your daddy", "Don't be a buster"] %>

    <div class="topnav">
    <a href="/">Home</a>
    <div class="dropdown">
      <button class="dropbtn"><a href="/years">Years</a>
        <i class="fa fa-caret-down"></i>
      </button>
      <div class="dropdown-content">
        <a href="/1990">1990</a>
        <a href="/1991">1991</a>
        <a href="/1992">1992</a>
        <a href="/1993">1993</a>
        <a href="/1994">1994</a>
        <a href="/1995">1995</a>
        <a href="/1996">1996</a>
        <a href="/1997">1997</a>
        <a href="/1998">1998</a>
        <a href="/1999">1999</a>
        </div>
      </div>
    <a href="/favorites">Favorites</a>
    <% if @logged_in_user %>
      <%= link_to 'Log Out', log_out_path, method: 'delete' %>
      <p class="right"><%= greetings.sample %>, <%= @logged_in_user.username %></p>
    <% else %>
      <a href="/login">Log In</a>
      <a href="/create_account">Create Account</a>
    <% end %>
    </div>
    
    <br><br><br>
    <%= yield %>

  </body>
</html>

app/views/users/create_account.html.erb
<div class="enter-info-page">

<h1>Create an Account</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <h2><%= message %></h2>
  <% end %>
<% end %>

  <div class="enter-info-form">
  <%= form_for @user do |f| %>
    <%= f.label "Enter a username:" %>
    <%= f.text_field :username %>
    <%= f.submit value: "Create Account" %>
  <% end %>
  </div>

<h2>Already have an account? <%= link_to 'Click here to log in!', login_path %></h2>

</div>

app/views/users/favorites.html.erb
<h1 class="year-header"><%= @logged_in_user.username %>'s favorite 90s stuff</h1>

<% unless @logged_in_user.has_any_favorites? %>
  <h1 class="go-add-favorites">Stop trippin', go add some favorites fool</h1>
<% else %>

<h2 class="subject-header">Favorite 90s Movies:</h2>

<div class="index-container">
  <% @favorite_movies.each do |movie| %>
  <div class="index-tile">
    <a href="<%= movie.external_link_1 %>"><img class="movie-img" src="<%=movie.img_url%>"></a>
      <p><em>Title:</em> <%= movie.title %></p>
      <p><em>Genre:</em> <%= movie.genre %></p>
      <p><em>Box Office:</em> <%= movie.box_office %></p>
      <p><em>Description:</em> <%= movie.description %></p>
      <a href="<%= movie.external_link_1 %>">Learn more about <%=movie.title%> on Wikipedia</a>
      <br><br>
      <a href="<%= movie.external_link_2 %>">Watch the trailer for <%=movie.title%> on YouTube</a>
      <br><br>
    <%= form_for :user_favorite, url: remove_from_favorites_path, method: :delete do |f| %>
      <%= f.hidden_field :movie_id, value: movie.id %>
      <%= f.submit value: "Remove from Favorites" %>
    <% end %>
  </div>
  <% end %>
</div>

<h2 class="subject-header">Favorite 90s Songs:</h2>

<div class="index-container">
  <% @favorite_songs.each do |song| %>
  <div class="index-tile">
    <a href="<%= song.external_link_1 %>"><img src="<%=song.img_url%>"></a>
    <p><em>Title:</em> <%= song.title %></p>
    <p><em>Artist:</em> <%= song.artist %></p>
    <p><em>Genre:</em> <%= song.genre %></p>
    <a href="<%= song.external_link_1 %>">Learn more about <%=song.title%> on Wikipedia</a>
    <br><br>
    <a href="<%= song.external_link_2 %>">Watch the music video for <%=song.title%> on YouTube</a>
    <br><br>
    <%= form_for :user_favorite, url: remove_from_favorites_path, method: :delete do |f| %>
      <%= f.hidden_field :song_id, value: song.id %>
      <%= f.submit value: "Remove from Favorites" %>
    <% end %>
    </div>
  <% end %>
</div>

<h2 class="subject-header">Favorite 90s Games:</h2>

<div class="index-container">
  <% @favorite_games.each do |game| %>
  <div class="index-tile">
    <a href="<%= game.external_link_1 %>"><img src="<%=game.img_url%>"></a>
    <p><em>Title:</em> <%= game.title %></p>
    <p><em>Genre:</em> <%= game.genre %></p>
    <p><em>Platform:</em> <%= game.platform %></p>
    <p><em>Publisher:</em> <%= game.publisher %></p>
    <p><em>Description:</em> <%= game.description %></p>
    <a href="<%= game.external_link_1 %>">Learn more about <%=game.title%> on Wikipedia</a>
    <br><br>
    <a href="<%= game.external_link_2 %>">Watch gameplay of <%=game.title%> on YouTube</a>
    <br><br>
    <%= form_for :user_favorite, url: remove_from_favorites_path, method: :delete do |f| %>
      <%= f.hidden_field :game_id, value: game.id %>
      <%= f.submit value: "Remove from Favorites" %>
    <% end %>
  </div>
  <% end %>
</div>
<br><br>

<% end %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <h2><%= message %></h2>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label "Enter a username:" %>
  <%= f.text_field :username %>
  <%= f.submit value: "Create User" %>
<% end %>

</div>

app/views/years/_form.html.erb
<h1 class="year-header">Welcome to the year <%= @year %>!</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <h2><%= message %></h2>
  <% end %>
<% end %>

<h2 class="subject-header">Top Box Office Hits from <%= @year %>:</h2>
<div class="index-container">
  <% @movies.each do |movie| %>
  <div class="index-tile">
      <a href="<%= movie.external_link_1 %>"><img class="movie-img" src="<%=movie.img_url%>"></a>
      <p><em>Title:</em> <%= movie.title %></p>
      <p><em>Genre:</em> <%= movie.genre %></p>
      <p><em>Box Office:</em> <%= movie.box_office %></p>
      <p><em>Description:</em></p> <p><%= movie.description %></p>
      <a href="<%= movie.external_link_1 %>">Learn more about <%=movie.title%> on Wikipedia</a>
      <br><br>
      <a href="<%= movie.external_link_2 %>">Watch the trailer for <%=movie.title%> on YouTube</a>
      <br><br>
      <% if @logged_in_user %>
        <%= form_for :user_favorite, url: add_to_favorites_path do |f| %>
          <%= f.hidden_field :movie_id, value: movie.id %>
          <%= f.submit value: "Add to Favorites" %>
        <% end %>
      <% end %>
    </div>
    <% end %>
</div>

<br>
<hr>
<br>

<h2 class="subject-header">Chart Toppers of <%= @year %>:</h2>
<div class="index-container">
  <% @songs.each do |song| %>
  <div class="index-tile">
    <a href="<%= song.external_link_1 %>"><img src="<%=song.img_url%>"></a>
    <p><em>Title:</em> <%= song.title %></p>
    <p><em>Artist:</em> <%= song.artist %></p>
    <p><em>Genre:</em> <%= song.genre %></p>
    <a href="<%= song.external_link_1 %>">Learn more about <%=song.title%> on Wikipedia</a>
    <br><br>
    <a href="<%= song.external_link_2 %>">Watch the music video for <%=song.title%> on YouTube</a>
    <br><br>
    <% if @logged_in_user %>
      <%= form_for :user_favorite, url: add_to_favorites_path do |f| %>
        <%= f.hidden_field :song_id, value: song.id %>
        <%= f.submit value: "Add to Favorites" %>
      <% end %>
    <% end %>
    </div>
  <% end %>
</div>

<br>
<hr>
<br>

<h2 class="subject-header">Hottest Video Games of <%= @year %>:</h2>
<div class="index-container">
  <% @games.each do |game| %>
  <div class="index-tile">
    <a href="<%= game.external_link_1 %>"><img src="<%=game.img_url%>"></a>
    <p><em>Title:</em> <%= game.title %></p>
    <p><em>Genre:</em> <%= game.genre %></p>
    <p><em>Platform:</em> <%= game.platform %></p>
    <p><em>Publisher:</em> <%= game.publisher %></p>
    <p><em>Description:</em></p> <p><%= game.description %></p>
    <a href="<%= game.external_link_1 %>">Learn more about <%=game.title%> on Wikipedia</a>
    <br><br>
    <a href="<%= game.external_link_2 %>">Watch gameplay of <%=game.title%> on YouTube</a>
    <br><br>
    <% if @logged_in_user %>
      <%= form_for :user_favorite, url: add_to_favorites_path do |f| %>
        <%= f.hidden_field :game_id, value: game.id %>
        <%= f.submit value: "Add to Favorites" %>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>
<br><br>

app/views/years/y_1990.html.erb
<%= render "form" %>

app/views/years/y_1991.html.erb
<%= render "form" %>

app/views/years/y_1992.html.erb
<%= render "form" %>

app/views/years/y_1993.html.erb
<%= render "form" %>

app/views/years/y_1994.html.erb
<%= render "form" %>

app/views/years/y_1995.html.erb
<%= render "form" %>

app/views/years/y_1996.html.erb
<%= render "form" %>

app/views/years/y_1997.html.erb
<%= render "form" %>

app/views/years/y_1998.html.erb
<%= render "form" %>

app/views/years/y_1999.html.erb
<%= render "form" %>

app/views/years/years.html.erb
<h1 class="years-page-header">Select a year:</h1>

<div class="years-box">
  <ul>
    <li><%= link_to '1990', '/1990' %></li>
    <li><%= link_to '1991', '/1991' %></li>
    <li><%= link_to '1992', '/1992' %></li>
    <li><%= link_to '1993', '/1993' %></li>
    <li><%= link_to '1994', '/1994' %></li>
    <li><%= link_to '1995', '/1995' %></li>
    <li><%= link_to '1996', '/1996' %></li>
    <li><%= link_to '1997', '/1997' %></li>
    <li><%= link_to '1998', '/1998' %></li>
    <li><%= link_to '1999', '/1999' %></li>
  </ul>
</div>